services:
  tournament-db:
    container_name: postrges-database
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - tournament-network
networks:
  tournament-network:
    driver: bridge
